# Generated by Django 3.2.5 on 2024-02-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('vendor', 'category_name')},
        ),
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together={('vendor', 'food_title')},
        ),
    ]
