# Generated by Django 3.2.5 on 2024-02-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20240202_2104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together=set(),
        ),
    ]
